import { NextResponse } from "next/server"
import { supabase } from "@/lib/supabase"
import puppeteer from "puppeteer"

export async function POST(req: Request) {
  try {
    const { handover_id } = await req.json()

    if (!handover_id) {
      return NextResponse.json(
        { success: false, error: "handover_id wajib" },
        { status: 400 }
      )
    }

    // 1. get handover
    const { data: handover, error } = await supabase
      .from("handover")
      .select("id, share_token, receipt_url")
      .eq("id", handover_id)
      .single()

    if (error || !handover) {
      return NextResponse.json(
        { success: false, error: "handover tidak ditemukan" },
        { status: 404 }
      )
    }

    // 2. idempotent check
    if (handover.receipt_url) {
      return NextResponse.json({
        success: true,
        skipped: true,
        receipt_url: handover.receipt_url
      })
    }

    // 3. fetch data (reuse API)
    const base = process.env.NEXT_PUBLIC_BASE_URL

    const res = await fetch(
      `${base}/api/handover/receipt-data?token=${handover.share_token}`
    )

    const data = await res.json()

    if (!res.ok || !data) {
      return NextResponse.json(
        { success: false, error: "gagal ambil data receipt" },
        { status: 500 }
      )
    }

    // 4. build HTML
    const itemsHtml = (data.handover_items || [])
      .map((i: any) => `<li>${i.description}</li>`)
      .join("")

    const html = `
      <html>
        <body style="font-family:sans-serif;padding:24px;">
          <h2>Serah Terima Paket</h2>
          <p><strong>Pengirim:</strong> ${data.sender_name || "-"}</p>
          <p><strong>Penerima:</strong> ${data.receiver_target_name || "-"}</p>
          <p><strong>Status:</strong> ${data.status}</p>

          <h4>Barang:</h4>
          <ul>${itemsHtml}</ul>

          <hr/>
          <p style="font-size:10px;">
            Generated by NEST System
          </p>
        </body>
      </html>
    `

    // 5. generate PDF
    const browser = await puppeteer.launch({
      args: ["--no-sandbox"]
    })

    const page = await browser.newPage()
    await page.setContent(html)

    const pdfBuffer = await page.pdf({
      format: "A4"
    })

    await browser.close()

    // 6. upload to storage
    const fileName = `receipt_${handover.id}.pdf`

    const { error: uploadError } = await supabase.storage
      .from("receipts")
      .upload(fileName, pdfBuffer, {
        contentType: "application/pdf",
        upsert: false
      })

    if (uploadError) {
      return NextResponse.json(
        { success: false, error: uploadError.message },
        { status: 500 }
      )
    }

    // 7. get public url
    const { data: publicUrlData } = supabase.storage
      .from("receipts")
      .getPublicUrl(fileName)

    const publicUrl = publicUrlData.publicUrl

    // 8. update DB
    await supabase
      .from("handover")
      .update({
        receipt_url: publicUrl,
        receipt_generated_at: new Date().toISOString()
      })
      .eq("id", handover.id)

    return NextResponse.json({
      success: true,
      receipt_url: publicUrl
    })

  } catch (error: any) {
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    )
  }
}