import { serve } from "https://deno.land/std/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js"
import { PDFDocument, rgb, StandardFonts } from "npm:pdf-lib"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

async function generatePDF(h: any, supabase: any) {
  const pdfDoc = await PDFDocument.create();
  // Ukuran 400x600 adalah identitas RECEIPTPAGE lu. Kita pertahankan.
  const page = pdfDoc.addPage([400, 600]);
  const { width, height } = page.getSize();
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  
  const margin = 35;
  let y = height - 45;

  // --- HEADER SECTION (PREMIUM LOOK) ---
  page.drawRectangle({ x: 0, y: y - 5, width: 5, height: 25, color: rgb(0, 0, 0) }); // Accent bar
  page.drawText("BUKTI SERAH TERIMA DIGITAL", { x: margin, y, size: 15, font: fontBold });
  y -= 15;
  page.drawText("NEST-System Official Receipt", { x: margin, y, size: 7, font: fontRegular, color: rgb(0.4, 0.4, 0.4) });
  
  y -= 35;

  // --- DATA MAPPING ---
  const items = h.package_items || h.handover_items || [];
  const event = h.receive_event?.[0] || {};

  // --- MAIN CONTENT AREA ---
  // Foto (Dibuat tajam dengan frame tipis)
  if (items[0]?.photo_url) {
    try {
      const { data: imgData } = await supabase.storage.from("nest-evidence").download(items[0].photo_url);
      if (imgData) {
        const img = await pdfDoc.embedJpg(await imgData.arrayBuffer());
        page.drawRectangle({ x: margin - 2, y: y - 82, width: 84, height: 84, color: rgb(0.9, 0.9, 0.9) }); // Outer frame
        page.drawImage(img, { x: margin, y: y - 80, width: 80, height: 80 });
      }
    } catch (e) {
      page.drawRectangle({ x: margin, y: y - 80, width: 80, height: 80, borderWidth: 0.5, borderColor: rgb(0.8, 0.8, 0.8) });
    }
  }

  // Info Detail (Sejajar Foto)
  const infoX = margin + 105;
  let infoY = y - 5;
  
  page.drawText("INFORMASI PENERIMAAN", { x: infoX, y: infoY, size: 7, font: fontBold, color: rgb(0.3, 0.3, 0.3) });
  infoY -= 15;
  page.drawText(`ID TRANSAKSI : ${h.id.substring(0, 12).toUpperCase()}`, { x: infoX, y: infoY, size: 8, font: fontBold });
  infoY -= 12;
  page.drawText(`PENERIMA     : ${h.receiver_target_name || '-'}`, { x: infoX, y: infoY, size: 8, font: fontRegular });
  infoY -= 10;
  page.drawText(`PENGIRIM     : ${h.sender_name || 'NEST User'}`, { x: infoX, y: infoY, size: 8, font: fontRegular });
  infoY -= 10;
  page.drawText(`WAKTU        : ${new Date(h.created_at).toLocaleString('id-ID')}`, { x: infoX, y: infoY, size: 8, font: fontRegular });

  y -= 110;

  // --- ITEM LIST (CLEAN TABLE STYLE) ---
  page.drawRectangle({ x: margin, y: y, width: width - (margin * 2), height: 1, color: rgb(0.8, 0.8, 0.8) });
  y -= 15;
  page.drawText("DAFTAR ITEM DALAM PAKET", { x: margin, y, size: 7, font: fontBold, color: rgb(0.3, 0.3, 0.3) });
  y -= 15;

  if (items.length > 0) {
    items.slice(0, 5).forEach((it: any, idx: number) => {
      const desc = it.description || it.name || 'Item tanpa deskripsi';
      page.drawText(`${idx + 1}.`, { x: margin, y, size: 8, font: fontBold });
      page.drawText(desc.substring(0, 50), { x: margin + 15, y, size: 8, font: fontRegular });
      y -= 12;
    });
  }

  // --- DIGITAL TRUST BLOCK (FOOTER AREA) ---
  const trustY = 125;
  // Background Box Official
  page.drawRectangle({ x: margin, y: trustY - 55, width: width - (margin * 2), height: 65, color: rgb(0.98, 0.98, 0.98) });
  page.drawRectangle({ x: margin, y: trustY + 10, width: width - (margin * 2), height: 1.5, color: rgb(0, 0, 0) }); // Top Divider

  page.drawText("DIGITAL TRUST VERIFICATION", { x: margin + 10, y: trustY - 5, size: 7, font: fontBold });
  
  const trustInfo = [
    `GEO-TAGGING : ${event.latitude || '-'}, ${event.longitude || '-'} (Verified GPS)`,
    `DEVICE ID   : ${event.device_info ? event.device_info.substring(0, 65) : 'Unknown Device'}`,
    `AUTH STATUS : DIGITAL SIGNATURE GENERATED BY NEST-CORE`,
    `TIMESTAMP   : ${h.receipt_generated_at || new Date().toISOString()}`
  ];

  let ty = trustY - 18;
  trustInfo.forEach(text => {
    page.drawText(text, { x: margin + 10, y: ty, size: 6, font: fontRegular, color: rgb(0.2, 0.2, 0.2) });
    ty -= 9;
  });

  // Disclaimer
  page.drawText("Dokumen ini adalah bukti sah yang dihasilkan secara otomatis dan tidak memerlukan tanda tangan basah.", { 
    x: margin, y: 40, size: 6, font: fontRegular, color: rgb(0.5, 0.5, 0.5) 
  });

  return await pdfDoc.save();
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    
    // Claim Job
    const { data: hJob, error: rpcError } = await supabase.rpc('claim_handover_receipt_job').single();
    if (rpcError || !hJob) return new Response(JSON.stringify({ message: "No job" }), { headers: corsHeaders, status: 200 });

    // Fetch Full Data (Mapping Ganda Handover & Package)
    const { data: full, error: fetchError } = await supabase
      .from("handover")
      .select("*, handover_items(*), package_items(*), receive_event(*)")
      .eq("id", hJob.id)
      .single();

    if (fetchError || !full) throw new Error("Data fetch failed");

    const pdfBytes = await generatePDF(full, supabase);
    const path = `paket/${full.user_id}/${full.id}/receipt_${full.id}.pdf`;
    
    // Storage Upload
    const { error: uploadError } = await supabase.storage.from("nest-evidence").upload(path, pdfBytes, { 
      contentType: "application/pdf", 
      upsert: true 
    });

    if (uploadError) throw new Error("Upload failed");

    // Finalize
    await supabase.from("handover").update({ receipt_url: path, receipt_status: "done" }).eq("id", full.id);
    
    return new Response(JSON.stringify({ status: "success", path }), { 
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }, 
      status: 200 
    });

  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { headers: corsHeaders, status: 500 });
  }
});